# Generated by Django 3.2 on 2022-09-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcoliscgdladet',
            old_name='code_trans',
            new_name='code_trans2',
        ),
    ]
