# Generated by Django 3.2 on 2022-09-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0002_rename_code_trans_transcoliscgdladet_code_trans2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcoliscgdladet',
            old_name='code_trans2',
            new_name='code_trans',
        ),
    ]
