# Generated by Django 3.2 on 2022-09-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0003_rename_code_trans2_transcoliscgdladet_code_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcoliscgdladet',
            name='destinataires',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Destinataire'),
        ),
    ]
