# Generated by Django 3.2 on 2022-09-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0004_transcoliscgdladet_destinataires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcoliscgdladet',
            old_name='destinataires',
            new_name='destinatairess',
        ),
        migrations.AlterField(
            model_name='transcoliscgdladet',
            name='code_trans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Code Transport'),
        ),
    ]
