# Generated by Django 3.2 on 2022-09-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0005_auto_20220925_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcoliscgdladet',
            name='destinatairess',
        ),
        migrations.AlterField(
            model_name='transcoliscgdladet',
            name='code_trans',
            field=models.ForeignKey(db_column='code_trans', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='betou.transcoliscgdla'),
            preserve_default=False,
        ),
    ]
