# Generated by Django 3.2 on 2022-09-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0010_alter_transcoliscgdladet_code_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcoliscgdladet',
            name='code_trans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='betou.transcoliscgdla'),
        ),
    ]
