# Generated by Django 3.2 on 2022-09-25 17:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0013_alter_transcoliscgdladet_code_trans'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transcoliscgdladet',
            managers=[
                ('transcolis', django.db.models.manager.Manager()),
            ],
        ),
    ]
