# Generated by Django 3.2 on 2022-09-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0014_alter_transcoliscgdladet_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transcoliscgdladet',
            managers=[
            ],
        ),
    ]
