# Generated by Django 3.2 on 2022-09-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0015_alter_transcoliscgdladet_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcoliscgdladet',
            name='code_trans',
            field=models.ForeignKey(db_column='code_trans', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='betou.transcoliscgdla'),
            preserve_default=False,
        ),
    ]
