# Generated by Django 3.2 on 2022-09-26 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0017_alter_transcoliscgdladet_code_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcoliscgdladet',
            name='id_trans_colis_cg_dla',
            field=models.ForeignKey(db_column='id_trans_colis_cg_dla', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.transcoliscgdla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcoliscgdladet',
            name='code_trans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Code Transport'),
        ),
    ]
