# Generated by Django 3.2 on 2022-09-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0018_auto_20220926_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='specifcoliscgdladet',
            name='id_specif_colis_cg_dla',
            field=models.ForeignKey(db_column='id_specif_colis_cg_dla', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.specifcoliscgdla'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specifgrumescgdladet',
            name='id_specif_grumes_cg_dla',
            field=models.ForeignKey(db_column='id_specif_grumes_cg_dla', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.specifgrumescgdla'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transgrumescgdladet',
            name='id_trans_grumes_cg_dla',
            field=models.ForeignKey(db_column='id_trans_grumes_cg_dla', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.transgrumescgdla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transgrumescgdla',
            name='code_trans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Code Transport'),
        ),
    ]
