# Generated by Django 3.2 on 2022-09-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0020_transcoliscgdladet_destinatairess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=100)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betou.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='transcoliscgdladet',
            name='destinatairess',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Price')),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='betou.category')),
                ('Item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='betou.item')),
            ],
        ),
    ]
