# Generated by Django 3.2 on 2022-09-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0021_auto_20220928_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Price_Item',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Price'),
        ),
    ]
