# Generated by Django 3.2 on 2022-09-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0022_item_price_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Item_Cat',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='Price_Cat',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Price'),
        ),
    ]
