# Generated by Django 3.2 on 2022-09-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0023_auto_20220928_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='I_Contrats',
            fields=[
                ('id_contrats', models.AutoField(primary_key=True, serialize=False)),
                ('num_contrat', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de Contrat')),
            ],
            options={
                'verbose_name': 'Contrat Importé Table Betou',
                'verbose_name_plural': 'Contrats Importés Table Betou',
                'db_table': 'I_Contrats',
                'ordering': ['num_contrat'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='I_Contrats_Gr',
            fields=[
                ('id_contrats_gr', models.AutoField(primary_key=True, serialize=False)),
                ('num_contrat_gr', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de Contrat Grumes')),
            ],
            options={
                'verbose_name': 'Contrat Grumes Importé Table Betou',
                'verbose_name_plural': 'Contrats Grumes Importés Table Betou',
                'db_table': 'I_Contrats_Gr',
                'ordering': ['num_contrat_gr'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='I_Essences',
            fields=[
                ('id_essences', models.AutoField(primary_key=True, serialize=False)),
                ('essence', models.CharField(blank=True, max_length=20, null=True, verbose_name='Essence')),
                ('nom_scientifique', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nom Scientifique')),
            ],
            options={
                'verbose_name': 'Essences Importées Table Betou',
                'verbose_name_plural': 'Essences Importées Table Betou',
                'db_table': 'I_Essences',
                'ordering': ['essence'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='I_Produits',
            fields=[
                ('id_produits', models.AutoField(primary_key=True, serialize=False)),
                ('produit', models.CharField(blank=True, max_length=25, null=True, verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Produits Importés Tables Betou',
                'verbose_name_plural': 'Produits Importés Table Betou',
                'db_table': 'I_Produits',
                'ordering': ['produit'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='I_Qualites',
            fields=[
                ('id_qualites', models.AutoField(primary_key=True, serialize=False)),
                ('qualite', models.CharField(blank=True, max_length=20, null=True, verbose_name='Qualité')),
            ],
            options={
                'verbose_name': 'Qualités Importées Tables Betou',
                'verbose_name_plural': 'Qualités Importées Table Betou',
                'db_table': 'I_Qualites',
                'ordering': ['qualite'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='I_Qualites_Gr',
            fields=[
                ('id_qualites_gr', models.AutoField(primary_key=True, serialize=False)),
                ('qualite_gr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Qualité Grumes')),
            ],
            options={
                'verbose_name': 'Qualités Grumes Importées Tables Betou',
                'verbose_name_plural': 'Qualités Grumes Importées Table Betou',
                'db_table': 'I_Qualites_Gr',
                'ordering': ['qualite_gr'],
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='specifcoliscgdla',
            name='num_contrat',
            field=models.ForeignKey(db_column='num_contrat', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.i_contrats'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specifcoliscgdladet',
            name='essence',
            field=models.ForeignKey(db_column='essence', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.i_essences'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specifcoliscgdladet',
            name='produit',
            field=models.ForeignKey(db_column='produit', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.i_produits'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specifcoliscgdladet',
            name='qualite',
            field=models.ForeignKey(db_column='qualite', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.i_qualites'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specifgrumescgdla',
            name='num_contrat',
            field=models.ForeignKey(db_column='num_contrat_gr', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.i_contrats_gr'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specifgrumescgdladet',
            name='essence',
            field=models.ForeignKey(db_column='essence', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.i_essences'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specifgrumescgdladet',
            name='qualite',
            field=models.ForeignKey(db_column='qualite_gr', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.i_qualites_gr'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcoliscgdladet',
            name='essence',
            field=models.ForeignKey(db_column='essence', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.i_essences'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcoliscgdladet',
            name='num_contrat',
            field=models.ForeignKey(db_column='num_contrat', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.i_contrats'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcoliscgdladet',
            name='produit',
            field=models.ForeignKey(db_column='produit', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.i_produits'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcoliscgdladet',
            name='qualite',
            field=models.ForeignKey(db_column='qualite', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.i_qualites'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transgrumescgdladet',
            name='essence',
            field=models.ForeignKey(db_column='essence', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.i_essences'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transgrumescgdladet',
            name='num_contrat',
            field=models.ForeignKey(db_column='num_contrat_gr', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.i_contrats_gr'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transgrumescgdladet',
            name='qualite',
            field=models.ForeignKey(db_column='qualite_gr', default='', on_delete=django.db.models.deletion.CASCADE, to='betou.i_qualites_gr'),
            preserve_default=False,
        ),
    ]
