# Generated by Django 3.2 on 2022-09-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0024_auto_20220929_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifcoliscgdladet',
            name='qualite',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Qualité'),
        ),
        migrations.AlterField(
            model_name='transcoliscgdladet',
            name='qualite',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Qualité'),
        ),
        migrations.DeleteModel(
            name='I_Qualites',
        ),
    ]
