# Generated by Django 3.2 on 2022-09-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0025_auto_20220929_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specifcoliscgdladet',
            name='longueur',
        ),
        migrations.RemoveField(
            model_name='transcoliscgdladet',
            name='longueur',
        ),
    ]
