# Generated by Django 3.2 on 2022-10-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betou', '0028_auto_20221001_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifgrumescgdladet',
            name='qualite',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Qualité'),
        ),
        migrations.AlterField(
            model_name='transgrumescgdladet',
            name='qualite',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Qualité'),
        ),
        migrations.DeleteModel(
            name='I_Qualites_Gr',
        ),
    ]
