# Generated by Django 3.2.8 on 2022-09-19 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='essence_famille',
            fields=[
                ('IdFamille', models.AutoField(primary_key=True, serialize=False)),
                ('Famille', models.CharField(max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "Famille de l'Essence",
                'verbose_name_plural': 'Famille des Essences',
                'db_table': 'essence_famille',
                'ordering': ['Famille'],
            },
        ),
        migrations.CreateModel(
            name='essence_groupe',
            fields=[
                ('IdGroupe', models.AutoField(primary_key=True, serialize=False)),
                ('Groupe', models.CharField(max_length=4, unique=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "Groupe de l'Essence",
                'verbose_name_plural': 'Groupes des Essences',
                'db_table': 'essence_groupe',
                'ordering': ['Groupe', 'Description'],
            },
        ),
        migrations.CreateModel(
            name='essences',
            fields=[
                ('IdEssence', models.AutoField(primary_key=True, serialize=False)),
                ('Essence', models.CharField(max_length=20, unique=True, verbose_name='Essence')),
                ('Classe', models.CharField(blank=True, choices=[('R', 'Bois Rouges'), ('B', 'Bois Blancs')], max_length=1, null=True)),
                ('Abreviation', models.CharField(blank=True, max_length=7, null=True, verbose_name='Abréviation')),
                ('CodeAdm', models.IntegerField(blank=True, null=True, verbose_name='Code Administration')),
                ('NomScientifique', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nom Scientifique')),
                ('Densite', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Densité')),
                ('DensiteFrais', models.IntegerField(blank=True, null=True, verbose_name='Densité Bois Frais')),
                ('DensiteSeche', models.IntegerField(blank=True, null=True, verbose_name='Densité Bois Séché')),
                ('NumEssence', models.IntegerField(verbose_name='Numéro Essence')),
                ('CoefA', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Coefficient A')),
                ('CoefB', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Coefficient B')),
                ('CoefC', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Coefficient C')),
                ('CoefD', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Coefficient D')),
                ('CoefE', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Coefficient E')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('IdFamille', models.ForeignKey(blank=True, db_column='IdFamille', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.essence_famille', verbose_name='Famille')),
                ('IdGroupe', models.ForeignKey(blank=True, db_column='IdGroupe', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.essence_groupe', verbose_name='Groupe')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Essence',
                'verbose_name_plural': 'Essences',
                'db_table': 'essences',
                'ordering': ['Essence'],
            },
        ),
        migrations.CreateModel(
            name='ufa',
            fields=[
                ('IdUfa', models.AutoField(primary_key=True, serialize=False)),
                ('Ufa', models.CharField(max_length=20, unique=True, verbose_name='UFA')),
                ('Volume', models.IntegerField(blank=True, null=True)),
                ('Superficie', models.IntegerField(blank=True, null=True)),
                ('Pieds', models.IntegerField(blank=True, null=True)),
                ('Date_ouverture', models.DateField(blank=True, null=True)),
                ('Date_fermeture', models.DateField(blank=True, null=True)),
                ('IdTitulaire', models.IntegerField(blank=True, null=True)),
                ('IdExploitant', models.IntegerField(blank=True, null=True)),
                ('IdRegions', models.IntegerField(blank=True, null=True)),
                ('IdMarteau', models.IntegerField(blank=True, null=True)),
                ('Observations', models.CharField(blank=True, max_length=200, null=True)),
                ('Reference', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "UFA - Unité Forestière d'Aménagement",
                'verbose_name_plural': "UFA - Unités Forestières d'Aménagements",
                'db_table': 'ufa',
                'ordering': ['Ufa'],
            },
        ),
        migrations.CreateModel(
            name='ufp',
            fields=[
                ('IdUfp', models.AutoField(primary_key=True, serialize=False)),
                ('Ufp', models.CharField(max_length=20)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Superficie', models.IntegerField(blank=True, null=True)),
                ('Date_ouverture', models.DateField(blank=True, null=True)),
                ('Date_fermeture', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('IdUfa', models.ForeignKey(db_column='IdUfa', on_delete=django.db.models.deletion.DO_NOTHING, to='tables.ufa', verbose_name='IdUfa')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'UFP - Unité Forestière de Production',
                'verbose_name_plural': 'UFP - Unités Forestières de Production',
                'db_table': 'ufp',
                'ordering': ['Ufp'],
                'unique_together': {('Ufp', 'IdUfa')},
            },
        ),
        migrations.CreateModel(
            name='titulaire',
            fields=[
                ('IdTitulaire', models.AutoField(primary_key=True, serialize=False)),
                ('Titulaire', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'db_table': 'titulaire',
            },
        ),
        migrations.CreateModel(
            name='taxe_abattage',
            fields=[
                ('IdTaxeAbattage', models.AutoField(primary_key=True, serialize=False)),
                ('DateTaxe', models.DateField()),
                ('ValeurFobZ1', models.IntegerField()),
                ('ValeurFobZ2', models.IntegerField()),
                ('ValeurFobZ3', models.IntegerField()),
                ('TaxePourcent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('IdEssence', models.ForeignKey(db_column='IdEssence', on_delete=django.db.models.deletion.CASCADE, to='tables.essences')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "Taxe d'abattage",
                'verbose_name_plural': "Taxes d'abattages",
                'db_table': 'taxe_abattage',
                'ordering': ['-DateTaxe'],
            },
        ),
        migrations.CreateModel(
            name='regions',
            fields=[
                ('IdRegions', models.AutoField(primary_key=True, serialize=False)),
                ('Regions', models.CharField(max_length=50)),
                ('Num_zone', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='marteau',
            fields=[
                ('IdMarteau', models.AutoField(primary_key=True, serialize=False)),
                ('Marteau', models.CharField(max_length=10, unique=True)),
                ('Proprietaire', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'db_table': 'marteau',
            },
        ),
        migrations.CreateModel(
            name='exploitant',
            fields=[
                ('IdExploitant', models.AutoField(primary_key=True, serialize=False)),
                ('Exploitant', models.CharField(max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'db_table': 'exploitant',
            },
        ),
        migrations.CreateModel(
            name='essence_detail',
            fields=[
                ('IdEssenceDetail', models.AutoField(primary_key=True, serialize=False)),
                ('DiaMini', models.IntegerField()),
                ('DiaMaxi', models.IntegerField()),
                ('TaxeAbattage', models.IntegerField()),
                ('QualiteExploitable', models.CharField(max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('IdEssence', models.ForeignKey(db_column='IdEssence', on_delete=django.db.models.deletion.CASCADE, to='tables.essences')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "Détail de l'Essence",
                'verbose_name_plural': 'Détail des Essences',
                'db_table': 'essence_detail',
                'ordering': ['DiaMini', 'DiaMaxi'],
            },
        ),
        migrations.CreateModel(
            name='abandon',
            fields=[
                ('IdAbandon', models.AutoField(primary_key=True, serialize=False)),
                ('Cause', models.CharField(max_length=15, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'db_table': 'abandon',
            },
        ),
        migrations.CreateModel(
            name='aac',
            fields=[
                ('IdAac', models.AutoField(primary_key=True, serialize=False)),
                ('Aac', models.CharField(max_length=20, verbose_name='AAC')),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Superficie_brute', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('Superficie_productive', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('Date_ouverture', models.DateField(blank=True, null=True)),
                ('Date_fermeture', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('IdUfp', models.ForeignKey(db_column='IdUfp', on_delete=django.db.models.deletion.DO_NOTHING, to='tables.ufp', verbose_name='IdUfp')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'AAC - Assiette Annuelle de Coupe',
                'verbose_name_plural': 'AAC - Assiettes Annuelles de Coupe',
                'db_table': 'Aac',
                'ordering': ['Aac'],
                'unique_together': {('Aac', 'IdUfp')},
            },
        ),
    ]
