# Generated by Django 3.2 on 2022-09-25 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('betou', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LieuReceptionDla',
            fields=[
                ('id_lieureceptiondla', models.AutoField(primary_key=True, serialize=False)),
                ('lieu_reception', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lieu de Réception')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Lieu de Réception Douala',
                'verbose_name_plural': 'Lieux de Réception Douala',
                'db_table': 'LieuReceptionDla',
                'ordering': ['lieu_reception'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecepTransSciages',
            fields=[
                ('id_receptranssciages', models.AutoField(primary_key=True, serialize=False)),
                ('code_reception', models.CharField(blank=True, max_length=12, null=True, verbose_name='Code Réception')),
                ('date_recep_trans', models.DateField(verbose_name='Date de Réception du Transport')),
                ('receptionnaire', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nom du réceptionnaire')),
                ('commentaires', models.CharField(blank=True, max_length=200, null=True, verbose_name='Commentaires')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code_trans', models.ForeignKey(db_column='code_trans', on_delete=django.db.models.deletion.DO_NOTHING, to='betou.transcoliscgdla')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('lieu_reception', models.ForeignKey(blank=True, db_column='lieu_reception', null=True, on_delete=django.db.models.deletion.CASCADE, to='douala.lieureceptiondla', verbose_name='Lieu de Réception')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Réception du Transport de Colis de Sciages de Bétou vers Douala',
                'verbose_name_plural': 'Réception de Transports de Colis de Bétou vers Douala',
                'db_table': 'RecepTransSciages',
                'ordering': ['code_trans'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecepTransGrumes',
            fields=[
                ('id_receptransgrumes', models.AutoField(primary_key=True, serialize=False)),
                ('code_reception', models.CharField(blank=True, max_length=12, null=True, verbose_name='Code Réception')),
                ('date_recep_trans', models.DateField(verbose_name='Date de Réception du Transport')),
                ('receptionnaire', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nom du réceptionnaire')),
                ('commentaires', models.CharField(blank=True, max_length=200, null=True, verbose_name='Commentaires')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code_trans', models.ForeignKey(db_column='code_trans', on_delete=django.db.models.deletion.DO_NOTHING, to='betou.transgrumescgdla')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('lieu_reception', models.ForeignKey(blank=True, db_column='lieu_reception', null=True, on_delete=django.db.models.deletion.CASCADE, to='douala.lieureceptiondla', verbose_name='Lieu de Réception')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Réception du Transport de Grumes de Bétou vers Douala',
                'verbose_name_plural': 'Réception de Transports de Grumes de Bétou vers Douala',
                'db_table': 'RecepTransGrumes',
                'ordering': ['code_trans'],
                'managed': True,
            },
        ),
    ]
