BBBB BBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX  XXXX XXXXXX XX XXX XXXXXXXXXXXXX XXXX XX XXXXX XXX XXXXXXXX XXX

BB BBBBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXX
      XXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBB