# Generated by Django 3.2.8 on 2022-09-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='Clé')),
                ('name', models.CharField(max_length=200, verbose_name='Réseau social')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Lien')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'lien',
                'verbose_name_plural': 'liens',
                'ordering': ['name'],
            },
        ),
    ]
